# --------------------------------------------------------------------------- #

stages:
  - test

variables:
  REPO_PATH: ${GOPATH}/src/gitlab.com/ArroyoNetworks

# == Unit Test Template ===================================================== #

._test: &test
  stage: test
  before_script:
    - mkdir -p ${REPO_PATH}
    - ln -s ${CI_PROJECT_DIR} ${REPO_PATH}/${CI_PROJECT_NAME}
    - cd ${REPO_PATH}/${CI_PROJECT_NAME}
    - go get .
  script:
    - go test -coverprofile /dev/null

# == Linux ================================================================== #

linux-go-1.7:
  image: golang:1.7
  <<: *test

# Specifically test against the version Arroyo service target.
linux-go-1.8.1:
  image: golang:1.8.1
  <<: *test

linux-go-1.8:
  image: golang:1.8
  <<: *test

linux-go-latest:
  image: golang:latest
  allow_failure: true
  <<: *test

# == macOS ================================================================== #

# Support Not Yet Implemented

# == Windows ================================================================ #

# Support Not Yet Implemented

# --------------------------------------------------------------------------- #